Added logic to load annoto completion conditions for annoto assighnments
Annoto/moodle-local_annoto pull request #135
Opened 2024-04-10 12:02 UTC by IlyaRazuvaev

https://app.clickup.com/t/86by58p2z

2024-04-28 19:37 UTC, genadis requested changes
why the source is not master branch but instead 5.1.0 tag?

2024-04-28 19:37 UTC, genadis commented on lib.php
> +            $deploymentdomain = 'annoto';
change to valid domain annoto.net

2024-04-28 19:37 UTC, genadis commented on lib.php
> +        $lti_config = lti_get_type_config($typeid);
fix variable name (run linter)

2024-04-30 15:56 UTC, IlyaRazuvaev commented
Can see only one branch now. Shouldn't be a problem as I see based on the file changes
![image](https://github.com/Annoto/moodle-local_annoto/assets/121438275/9b0012f8-6958-4710-aef6-ff706fb4d2c5)

2024-04-30 20:18 UTC, genadis approved these changes

2024-04-30 20:19 UTC, merged